# **Numpy**

* **NumPy (Numerical Python)** is a powerful Python library used for **numerical
computations**. It provides support for **multidimensional arrays** (ndarrays), **mathematical functions**, **linear algebra**, **random number generation**, and more.
* NumPy is especially useful for data science, machine learning, and scientific computing, as it allows fast operations on large datasets using vectorized code.

Installing numpy
* using pip
    - `pip install numpy`
* using uv
    - `uv add numpy`

## **Importing and creating numpy arrays**

In [2]:
import numpy as np

In [3]:
#creating a 1d numpy array
arr1 = np.array([1, 2, 3, 4])
print("1D array:", arr1)

#type
print(type(arr1))

# we can pass list, tuple input to array
arr2 = np.array((5, 6, 7, 8))
print("\n1D array:", arr2)
print(type(arr2))


1D array: [1 2 3 4]
<class 'numpy.ndarray'>

1D array: [5 6 7 8]
<class 'numpy.ndarray'>


In [4]:
# knowing the dimentions of array -- ndim

print(arr1.ndim)
print(arr2.ndim)

1
1


In [5]:
# creating a 2d numpy array

arr3 = np.array([[1.0, 2, 3], [4, 5, 6]])
print("2D array:\n", arr3)
print("dimention of the 2d array is : ", arr3.ndim)

2D array:
 [[1. 2. 3.]
 [4. 5. 6.]]
dimention of the 2d array is :  2


In [6]:
# creating a 3d numpy array

arr4 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print("3D array:\n", arr4)
print("\ndimention of 3d array is : ", arr4.ndim)

3D array:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

dimention of 3d array is :  3


In [7]:
# can also define dimention

arr5 = np.array([1, 2, 3, 4], ndmin=5)
print(arr5)
print('number of dimensions :', arr5.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [8]:
# Array of zeros

zeros_arr = np.zeros((2, 3))  # 2 rows, 3 columns
print("Zeros array:\n", zeros_arr)

Zeros array:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [9]:
# array of ones

ones_arr = np.ones((3, 2))
print("Ones array:\n", ones_arr)

Ones array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]


In [10]:
# Empty array (contains garbage values)

empty_arr = np.empty((2, 2))
print("Empty array:\n", empty_arr)

Empty array:
 [[6.23042070e-307 4.67296746e-307]
 [1.69121096e-306 0.00000000e+000]]


In [11]:
# Array with a range of values -- np.arange()

range_arr = np.arange(0, 10, 2)  # start, stop, step
print("Range array:", range_arr)

Range array: [0 2 4 6 8]


In [12]:
# Array with evenly spaced values -- linspace()

lin_arr = np.linspace(0, 1, 5)  # start, stop, num points
print("Linspace array:", lin_arr)
print("shape of the resulted lin space array is:", lin_arr.shape)

Linspace array: [0.   0.25 0.5  0.75 1.  ]
shape of the resulted lin space array is: (5,)


In [13]:
# Identity matrix

identity = np.eye(3)  # 3*3 identity matrix
print("Identity matrix:\n", identity)
print("Shape of identity matrix:", identity.shape)

Identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Shape of identity matrix: (3, 3)


In [14]:
# Full array with a constant value

filled = np.full((2, 3), 7) # 3*3 array with all values as 7
print("Full array with 7s:\n", filled)
print("Shape of full array:", filled.shape)

Full array with 7s:
 [[7 7 7]
 [7 7 7]]
Shape of full array: (2, 3)


## Array properties

In [15]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [16]:
# Shape – returns a tuple of dimensions (rows, cols)

print("Shape:", arr.shape)

Shape: (2, 3)


In [17]:
# Number of dimensions

print("Dimensions (ndim):", arr.ndim)

Dimensions (ndim): 2


In [18]:
# Total number of elements

print("Size:", arr.size)

Size: 6


In [19]:
# dtype -- Data type of array elements

print("Data type (dtype):", arr.dtype)

Data type (dtype): int64


In [20]:
# Changing dtype while creating

float_arr = np.array([1, 2, 3], dtype=float)
print("Float array:", float_arr)
print("New dtype:", float_arr.dtype)

Float array: [1. 2. 3.]
New dtype: float64


## Indexing and slicing

In [21]:
arr1 = np.array([10, 20, 30, 40, 50])

In [22]:
print("Element at index 2:", arr1[2])
print("Slicing [1:4]:", arr1[1:4])
print("Reverse array:", arr1[::-1])

Element at index 2: 30
Slicing [1:4]: [20 30 40]
Reverse array: [50 40 30 20 10]


In [23]:
arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print("Element at [1][2]:", arr2[1, 2])
print("Element at [1][2]", arr2[1][2])
print("First row:", arr2[0])
print("Second column:", arr2[:, 1])
print("Submatrix [0:2, 1:3]:\n", arr2[0:2, 1:3])

Element at [1][2]: 6
Element at [1][2] 6
First row: [1 2 3]
Second column: [2 5 8]
Submatrix [0:2, 1:3]:
 [[2 3]
 [5 6]]


In [24]:
# Negative indexing

print("Last row:", arr2[-1])
print("Last column:", arr2[:, -1])

Last row: [7 8 9]
Last column: [3 6 9]


In [25]:
# Boolean indexing

arr3 = np.array([5, 10, 15, 20, 25])
print("Values > 15:", arr3[arr3 > 15])

Values > 15: [20 25]


In [26]:
# Using condition on 2D array
print(arr2 % 2 == 0)

print("Even elements:\n", arr2[arr2 % 2 == 0])

[[False  True False]
 [ True False  True]
 [False  True False]]
Even elements:
 [2 4 6 8]


## **Array operations in numpy**

In [27]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [28]:
# Element-wise arithmetic

print("Addition:", a + b)
print("Subtraction:", b - a)
print("Multiplication:", a * b)
print("Division:", b / a)

Addition: [5 7 9]
Subtraction: [3 3 3]
Multiplication: [ 4 10 18]
Division: [4.  2.5 2. ]


In [29]:
# Element-wise power and modulus

print("Power:", a ** 2)
print("Modulus:", b % a)
print("ModulusL", a%2)

Power: [1 4 9]
Modulus: [0 1 0]
ModulusL [1 0 1]


In [30]:
# Scalar operations

print(a)
print("Add scalar:", a + 10)
print("Multiply scalar:", a * 2)
print("Subtract scalar:", a - 10)
print("Divide scalar:", a / 2)

[1 2 3]
Add scalar: [11 12 13]
Multiply scalar: [2 4 6]
Subtract scalar: [-9 -8 -7]
Divide scalar: [0.5 1.  1.5]


In [31]:
# Comparison

print("a > 2:", a > 2)
print("Equal:", a == b)
print("Equal:", a == 2.0)

a > 2: [False False  True]
Equal: [False False False]
Equal: [False  True False]


In [32]:
# Logical operations
print(a)
print(b)

print("Logical AND:", np.logical_and(a < 3, b > 4))
print("Logical OR:", np.logical_or(a == 2, b == 6))

[1 2 3]
[4 5 6]
Logical AND: [False  True False]
Logical OR: [False  True  True]


## **Mathematical operations on numpy**

In [33]:
arr = np.array([1, 2, 3, 4, 5])

In [34]:
# Basic statistics

print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))
print("Median:", np.median(arr))
print("Min:", np.min(arr))
print("Max:", np.max(arr))
print("Standard Deviation:", np.std(arr))
print("Variance:", np.var(arr))

Sum: 15
Mean: 3.0
Median: 3.0
Min: 1
Max: 5
Standard Deviation: 1.4142135623730951
Variance: 2.0


In [35]:
# Math operations

print("Square root:", np.sqrt(arr))
print("Exponential:", np.exp(arr))
print("Natural Logarithm:", np.log(arr))

Square root: [1.         1.41421356 1.73205081 2.         2.23606798]
Exponential: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
Natural Logarithm: [0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [36]:
# Rounding

decimals = np.array([3.14159, 2.71828, 1.61803])
print("Rounded:", np.round(decimals, 2))
print("Floor:", np.floor(decimals))
print("Ceil:", np.ceil(decimals))

Rounded: [3.14 2.72 1.62]
Floor: [3. 2. 1.]
Ceil: [4. 3. 2.]


## **Reshaping and manipulating arrays**

In [37]:
arr = np.arange(1, 13)

print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [38]:
# Reshape to 2D (3 rows, 4 columns)

reshaped = arr.reshape(3, 4)
print("Reshaped (3x4):\n", reshaped)

Reshaped (3x4):
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [39]:
# Flatten the array (1D)

flat = reshaped.flatten()
print("Flattened:", flat)

flat = reshaped.reshape(-1)
print("Flattened:", flat)

Flattened: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Flattened: [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [40]:
# Transpose

transposed = reshaped.T
print("Transposed:\n", transposed)

Transposed:
 [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [41]:
# Resize array inplace

resized = arr.copy()
resized.resize((2, 6))
print("Resized (2x6):\n", resized)

Resized (2x6):
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [42]:
# Stacking arrays vertically and horizontally

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

print(a)
print(b)

v_stack = np.vstack((a, b))
h_stack = np.hstack((a, b))
print("Vertical Stack:\n", v_stack)
print("Horizontal Stack:\n", h_stack)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
Vertical Stack:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Horizontal Stack:
 [[1 2 5 6]
 [3 4 7 8]]


In [43]:
# Splitting arrays

arr2 = np.array([10, 20, 30, 40, 50, 60])
split_arr = np.split(arr2, 3)
print("Split into 3 parts:", split_arr)

Split into 3 parts: [array([10, 20]), array([30, 40]), array([50, 60])]


## **numpy copy() vs view()**

In [44]:
original = np.array([10, 20, 30, 40])
print("original array:", original)

original array: [10 20 30 40]


In [45]:
# View (creates a reference, not a new object)
view_arr = original[1:3]
print("View:", view_arr)


# Modifying the view affects original
view_arr[0] = 999
print("Modified view:", view_arr)
print("Original after view change:", original)

View: [20 30]
Modified view: [999  30]
Original after view change: [ 10 999  30  40]


In [46]:
# Copy (creates a new independent object)
copy_arr = original.copy()
copy_arr[0] = 111
print("Copy:", copy_arr)
print("Original after copy change:", original)

# To verify object identity
print("View is original slice:", view_arr.base is original)
print("Copy is original slice:", copy_arr.base is original)

Copy: [111 999  30  40]
Original after copy change: [ 10 999  30  40]
View is original slice: True
Copy is original slice: False


## **Random module in numpy**

In [47]:
# seed for reproducability

np.random.seed(42)

In [48]:
# Random float array (0 to 1)

rand_arr = np.random.rand(2, 3)
print("Random float array:\n", rand_arr)

Random float array:
 [[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]]


In [49]:
# Standard normal distribution (mean=0, std=1)

normal_arr = np.random.randn(3)
print("Random normal values:", normal_arr)

Random normal values: [ 1.57921282  0.76743473 -0.46947439]


In [50]:
# Random integers from 10 to 99

rand_ints = np.random.randint(10, 100, size=(2, 4))
print("Random integers:\n", rand_ints)

Random integers:
 [[73 69 30 42]
 [85 67 31 98]]


In [51]:
# Random choice from a list

choice = np.random.choice([10, 20, 30, 40])
print("Random choices:", choice)

Random choices: 10


In [52]:
# shuffle inplace

arr = np.array([1, 2, 3, 4, 5])
np.random.shuffle(arr)
print("Shuffled array:", arr)

Shuffled array: [1 2 4 5 3]


In [53]:
# pick random elements without replacement

pick = np.random.choice(np.arange(100), size=5, replace=False)
print("Unique picks:", pick)

Unique picks: [48 71 12 26 45]


## **Linear algebra with numpy**

In [54]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[2, 0], [1, 2]])

print(A)
print("--"*4)
print(B)

[[1 2]
 [3 4]]
--------
[[2 0]
 [1 2]]


In [55]:
# Matrix multiplication (dot product)

dot_product = np.dot(A, B)
print("Dot product:\n", dot_product)

Dot product:
 [[ 4  4]
 [10  8]]


In [56]:
# Matrix transpose
print("Transpose of A:\n", A.T)

Transpose of A:
 [[1 3]
 [2 4]]


In [57]:
# Matrix inverse

inv_A = np.linalg.inv(A)
print("Inverse of A:\n", inv_A)

Inverse of A:
 [[-2.   1. ]
 [ 1.5 -0.5]]


In [58]:
# Determinant of A

det_A = np.linalg.det(A)
print("Determinant of A:", det_A)

Determinant of A: -2.0000000000000004


In [59]:
# Eigenvalues and eigenvectors

eigenvalues, eigenvectors = np.linalg.eig(A)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

Eigenvalues: [-0.37228132  5.37228132]
Eigenvectors:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [60]:
# Solve linear system: Ax = b

b = np.array([5, 11])
x = np.linalg.solve(A, b)
print("Solution of Ax = b:", x)

Solution of Ax = b: [1. 2.]


## **Saving and loading of numpy arrays**

In [61]:
arr = np.array([[10, 20, 30], [40, 50, 60]])

In [62]:
# Save array to a .npy file
np.save('my_array.npy', arr)

In [63]:
# Load it back
loaded_arr = np.load('my_array.npy')
print("Loaded array from .npy:\n", loaded_arr)

Loaded array from .npy:
 [[10 20 30]
 [40 50 60]]
